[package]
name = "statistic_physics"
version = "0.1.0"
edition = "2024"

[dependencies]

fixed = "1.29.0"
cordic = "0.1.5"
wacky_bag = {path="../wacky_bag"}
wacky_bag_fixed = {path="../wacky_bag_fixed"}
rand = "0.8.5"
physics_basic = {path="../physics_basic"}
frunk = "0.4.3"
lazy_static = "1.5.0"